In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import pandas as pd
import uuid
import time

options = Options()
options.add_argument("--headless")
driver = webdriver.Chrome(options=options)

product_urls = {
    "Toner mist": "https://kaspi.kz/shop/p/skin1004-mist-hyalu-cica-cloudy-120-ml-104904631/?0&c=750000000&ref=shared_link",
    "Dr.Althea 345": "https://kaspi.kz/shop/p/dr-althea-krem-345-relief-dlja-litsa-50-ml-115616909/?0&c=750000000&ref=shared_link",
    "Lagom": "https://kaspi.kz/shop/p/lagom-krem-cellus-mild-moisture-dlja-litsa-80-ml-100676372/?0&c=750000000&ref=shared_link",
    "telescopic тушь": "https://kaspi.kz/shop/p/tush-dlja-resnits-loreal-paris-telescopic-explosion-dlja-ob-ema-udlinjajuschaja-chernyi-17400312/?c=750000000&ref=shared_link",
    "Бальзам": "https://kaspi.kz/shop/p/fito-kosmetik-bal-zam-vazelin-uvlazhnenie-i-zaschita-10-102666500/?c=750000000&sr=6&qid=d4e7e5efef9988a52ecc9c155959dd20&ref=shared_link",
    "relouis пудра ": "https://kaspi.kz/shop/p/pudra-relouis-hd-powder-fixing-transparent-rassypchataja-01-belyi-100968225/?c=750000000&sr=1&qid=d285461498d0d5703498499264187614&ref=shared_link"
}

all_reviews = []

for product_name, url in product_urls.items():
    driver.get(url)
    time.sleep(4)
    collected = 0

    while True:
        soup = BeautifulSoup(driver.page_source, "html.parser")
        reviews = soup.find_all("div", class_="reviews__review")

        for review in reviews:
            if collected >= 100:  # Көбірек пікір жинау үшін 100-ге дейін көбейтуге болады
                break

            review_id = str(uuid.uuid4())

            date_tag = review.find("div", class_="reviews__date")
            date = date_tag.text.strip() if date_tag else None

            user_tag = review.find("div", class_="reviews__author")
            user = user_tag.text.strip() if user_tag else "Аноним"

            comment_tag = review.find("div", class_="reviews__review-text")
            comment = comment_tag.get_text(strip=True).replace("Комментарий:", "") if comment_tag else None

            rating_tag = review.find("div", class_=lambda c: c and "rating" in c)
            rating = None
            if rating_tag:
                classes = rating_tag.get("class")
                for cls in classes:
                    if cls.startswith("_"):
                        try:
                            rating = int(cls[1:]) / 10
                        except ValueError:
                            rating = None

            all_reviews.append({
                "ID": review_id,
                "Атауы": product_name,
                "Күні": date,
                "Пайдаланушы": user,
                "Баға": rating,
                "Пікір": comment
            })

            collected += 1

        # 👉 Келесі бетке өту батырмасын іздеу
        try:
            next_button = driver.find_element(By.XPATH, "//button[contains(@class, 'reviews__load-more')]")
            driver.execute_script("arguments[0].click();", next_button)
            time.sleep(3)
        except:
            break  # Егер "келесі" батырмасы жоқ болса, циклді тоқтату

driver.quit()

df = pd.DataFrame(all_reviews)
df.to_csv("Kaspi_pikirleri.csv", index=False, encoding='utf-8-sig')
print(f"✅ {len(all_reviews)} пікір сәтті сақталды!")

✅ 54 пікір сәтті сақталды!

In [3]:
df = pd.read_csv("Kaspi_pikirleri.csv")
df

,ID,Атауы,Күні,Пайдаланушы,Баға,Пікір
0,7bb7bf04-3f0e-4644-97c4-9a3628d703f7,Toner mist,17.06.2024,Ирина,5.0,Впервые пробую этот мист. Мне понравился. Осве...
1,188d59ae-9b0b-4d84-ab51-e5851bb17b18,Toner mist,28.02.2023,Наргиза,4.0,"Достоинства:Удобно брызгать, расход небольшой...."
2,bee59cfd-bec3-415c-b51f-e0561aba202e,Toner mist,23.09.2024,Нұрайлым,5.0,"Құрбымнан көріп алғанмын, бетім құрғақ болғасы..."
3,bad2d4e1-ef07-4409-98b4-a40691ab8908,Toner mist,13.07.2024,Ақерке,5.0,"Очень классная, качество супер, советую взять...."
4,59339bf1-cd51-4196-b7df-9f3e8e59af10,Toner mist,24.03.2024,Гульзада,3.0,"Мист шашатын жері істен шыққан, брак, сатушыға..."
5,07c74f6f-e813-4ed2-ae67-01facb4ee03e,Toner mist,14.04.2025,Рита,5.0,"Немного шиплет от того, что сразу даёт эффекты..."
6,39030f7b-7404-4922-8ff2-02c8a7175e28,Toner mist,04.02.2025,Коркем,5.0,Вся серия Skin 1004 супер! Каспи как всегда лу...
7,a4a1e0c7-a979-4e8e-9be1-12c2e61cd23d,Toner mist,17.01.2025,Сымбат,5.0,Товар оригинал! Спасибо большое магазину Korea...
8,2409f433-dfad-40e7-9fb0-5d6563c00db2,Toner mist,04.12.2024,Женіс,5.0,Күшті.0 человек(а) посчитал(и) отзыв полезным
9,a156fc93-c371-4fa0-90de-3c2aeff44c8e,Dr.Althea 345,15.02.2024,Лилия,5.0,"Самый лучший, лёгкий, не вызывает аллергию, пр..."
10,bddb3b2a-fea7-42b3-9c93-8623eee18e9e,Dr.Althea 345,15.04.2025,Гавхар,5.0,"Я никогда не оставляю отзыв, сегодня решила на..."
11,6577a113-fe54-4ad3-83d4-866deeea3273,Dr.Althea 345,03.01.2025,Индира,1.0,"Мне не подошел, не впитывается до конца, липко..."
12,56c60259-7d3e-4f76-b515-c7de618bba28,Dr.Althea 345,18.04.2025,Айтолқын,5.0,"Спасибо, проверила оригинал.3 человек(а) посчи..."
13,da305363-2699-40dd-a13a-0a9cc1bd56ae,Dr.Althea 345,12.11.2024,Ирина,5.0,"Огромное спасибо магазину POSH, доставили зака..."
14,631c65ea-dbc3-4c29-bcf9-560949fe7b9e,Dr.Althea 345,15.10.2024,Александра,5.0,Крем отлично подошел для моей жирной проблемно...
15,b73f7c40-f630-4573-9b4b-e7209b54e102,Dr.Althea 345,11.03.2025,Малика,5.0,"Заказывала уже во второй раз, оригинал. Пока э..."
16,b8b4b5b4-ef84-4215-94b3-68eb15086c7d,Dr.Althea 345,20.02.2025,Айнур,3.0,"Мне не подошло! Нет никакого увлажнения, кожа ..."
17,722592cf-e5d4-4022-9a07-2de70d2fab4d,Dr.Althea 345,17.01.2025,Азиза,4.0,"Неплохой легкий крем с ниацинамидом в составе,..."
18,9e6a7869-1ec2-4714-9a56-7ccee3c143ad,Lagom,10.03.2022,Антон,5.0,"Купил даме сердца, она им намазала лицо и сраз..."
19,bd6d5e71-90e9-426d-8838-56cf9c6e48c3,Lagom,29.06.2023,Сымбат,0.0,"80мг написано в упаковке, но внутри нет и 20м..."
20,45945bda-ad7b-4850-8824-c34f6ae8b05d,Lagom,03.08.2022,Жанаргуль,5.0,Достоинства:Ламеллярная формула. Качество. Увл...
21,bb5ea459-6b62-446f-92ab-9d397b143366,Lagom,31.08.2022,Сауле,3.0,"Достоинства:Быстро впитывается, нежирный.Станд..."
22,b91d2a6a-9bfa-4b49-8e0f-429951245e85,Lagom,15.03.2022,Дильназ,5.0,"Наношу данный крем днём, нормальный. Самое гла..."
23,f1dab223-f8cf-4a8c-ac26-561cdfb12e9d,Lagom,20.12.2021,Дина,5.0,"Достоинства:Эта фирма мой фаворит. Жаль, они в..."
24,186471a9-92f7-4c7e-9fb8-ef2aab6f903f,Lagom,05.02.2024,Алена,1.0,Купила в надежде на восстановление кожного бар...
25,2ad6c188-37b6-4053-bb30-f2afc5fce3f3,Lagom,08.05.2023,Мадина,1.0,"Крем купила по положительным отзывам, должен б..."
26,b0ed207e-981d-40a1-b774-f96e86d0fcce,Lagom,12.09.2022,Асхат,2.0,Недостатки:Не для жирной кожи точно! Забивает ...
27,8212d076-5521-4b70-99e3-dafcca21a23f,telescopic тушь,06.12.2021,Венера,5.0,"Достоинства:Я была в стельку пьяная, с парнем ..."
28,3c73f8f6-e01c-40ba-acd2-7b455308821a,telescopic тушь,03.09.2022,Анастасия,5.0,Достоинства:Устойчива к слезам. Удобна в приме...
29,7361f717-6bab-47a2-b140-76cae89952a1,telescopic тушь,21.07.2021,Айнур,1.0,"Недостатки:Ужасная тушь, повелась на отзывы, р..."
30,18f3f9b5-4fb1-41cc-bc17-e7755d79c6f8,telescopic тушь,13.01.2020,Асель,5.0,"Советую всем. Не первый год с этой тушью, удли..."
31,70a69a1f-40c6-488d-b25c-beea350d7edd,telescopic тушь,13.01.2020,Анар,5.0,"Достоинства:Очень хорошая тушь, классно удлиня..."
32,3773cfd9-ea9f-454d-a076-274704ba94db,telescopic тушь,06.01.2020,Ольга,4.0,Достоинства:Хорошая удлиняющая тушь.40 человек...
33,c0457a1d-6737-43a8-ba36-5d7206698a68,telescopic тушь,06.09.2024,Айдана,1.0,"Оригинал емес, салыстырмалы түрде оригинал туш..."
34,fe04f669-eee0-423f-b737-651c4db0eae4,telescopic тушь,05.01.2023,Кристина,5.0,"Достоинства:Самая лучшая тушь, прошлась пару р..."
35,e3d524c2-a97b-4265-82a6-99f6d610e833,telescopic тушь,12.12.2023,Милана,5.0,"Я рыдала целых 2 серии дорамы, тушь на месте, ..."
36,9ffccafd-ba0e-41e0-b54c-9ddc6634e3fd,Бальзам,07.12.2021,Евгения,5.0,"Достоинства:Мягкий, комфортный в нанесении, с ..."
37,3f7bf41b-21d5-4947-9b79-203cf164baf7,Бальзам,04.03.2024,Зулхумор,5.0,Ерінге арналған бальзамдар арасындағы ең керем...
38,1fbc06bb-0e7f-454c-805a-3d0f425f724e,Бальзам,22.10.2022,Виктория,5.0,"Достоинства:Приятно пахнет, хорошо увлажняет г..."
39,548e0625-20f6-46dc-9c37-35dc69bf7dec,Бальзам,21.10.2022,Кундыз,5.0,Достоинства:Запах нежный. Очень хороший вазели...
40,f9883215-7181-410a-a1d3-622554c6a55b,Бальзам,13.10.2022,Еңлік,5.0,"Достоинства:Хороший, увлажняет, легко наноситс..."
41,4e997355-c8ea-4103-95fc-937a500bc6af,Бальзам,18.10.2022,Елена,5.0,Достоинства:Хороший вазелин.3 человек(а) посчи...
42,a4e69f7a-921c-4f46-b478-789e8a0456d8,Бальзам,11.10.2022,Саяжан,5.0,Достоинства:После первого применения уже видно...
43,716d3883-f122-4890-9700-bcfdbccd2fd0,Бальзам,27.02.2025,Нұрай,5.0,"Ерні қыста да, жазда да жарылып үнемі бальзам ..."
44,393e6901-e609-4e26-aafe-315ff33b3e1b,Бальзам,22.12.2024,Рита,5.0,"Единственное, что спасает мои губы зимой, прия..."
45,476ac009-cb81-4a50-a6c0-c596510f4f82,relouis пудра,21.04.2023,Карима,1.0,"Недостатки:Неудобно открывать, сыплется ужасно..."
46,27215969-ec71-4efb-ac79-2069dc69eb80,relouis пудра,26.08.2022,Жамоат,3.0,"Достоинства:Большой объем, матирует очень хоро..."
47,ce6aee66-528c-4c27-a06c-a3625eb0f439,relouis пудра,26.10.2022,Альмира,3.0,"Достоинства:Сама пудра отличная, довольна.Недо..."
48,bfbfb0ab-8228-42b2-a32e-51a14e0e5aa1,relouis пудра,16.07.2021,Гүлназ,5.0,Достоинства:Пудра просто супер.Подходит для лю...
49,6ca1171e-7709-4c4f-a72c-1cb201810701,relouis пудра,20.01.2024,Тамила,5.0,"Самая лучшая пудра для меня, пользуюсь ей почт..."
50,7ce3a2bd-569f-43c1-962c-90ef059f9775,relouis пудра,25.04.2022,Сара,5.0,"Достоинства:Очень классная пудра, невесомая и ..."
51,075babc5-5975-468d-ac33-d6ea14aa10cb,relouis пудра,09.06.2022,Марина,4.0,Достоинства:Хорошо матирует.8 человек(а) посчи...
52,a861e6c2-00d8-4767-9adb-61c77c65ce61,relouis пудра,17.12.2024,Юлия,5.0,"Пудра классная, предупреждаю, сронжа в наборе ..."
53,a01cac0f-a516-4eec-8a92-1f39021eeffc,relouis пудра,24.04.2024,Аружан,1.0,Придаёт эффект сухой кожи.7 человек(а) посчита...

In [31]:
import re
from langdetect import detect

# Функция пікірдің тілін тексеру және қазақ/орыс тілін анықтау
def is_valid_language(text):
    try:
        language = detect(text)
        return language in ['kk', 'ru']  # Тек қазақ және орыс тілдерін қалдырамыз
    except:
        return False

# Пікірді тазарту: артық сөздер мен символдарды алып тастау
def clean_text(text):
    if not text:
        return ""
    # Артық символдарды алып тастау
    text = re.sub(r'\s+', ' ', text)  # Көп бос орынды бір бос орынмен ауыстыру
    text = re.sub(r'[^\w\s,.-]', '', text)  # Тек әріптер мен сандар, үтір, нүкте, сызықшалар қалдыру
    return text.strip()

# Тазарту процесі
df['Пікір'] = df['Пікір'].apply(lambda x: clean_text(x) if is_valid_language(x) else "")

In [32]:
# Пікір ұзындығын есептеу
df['Пікір Ұзындығы'] = df['Пікір'].apply(lambda x: len(str(x)) if x else 0)

# Баға бағанын сандық форматқа түрлендіру
df['Баға'] = pd.to_numeric(df['Баға'], errors='coerce')  # Қате мәндерді NaN деп қалдырады

In [33]:
# Деректерді CSV файлында сақтау
df.to_csv("Kaspi_pikirleri_cleaned.csv", index=False, encoding='utf-8-sig')

In [34]:
df = pd.read_csv("Kaspi_pikirleri_cleaned.csv")
df

,ID,Атауы,Күні,Пайдаланушы,Баға,Пікір,Пікір Ұзындығы
0,30413d14-73ba-4504-95d2-956bf19e5e58,Toner mist,17.06.2024,Ирина,5.0,Впервые пробую этот мист. Мне понравился. Осве...,238
1,28260584-9a26-40f2-b098-fe1813936ffb,Toner mist,28.02.2023,Наргиза,4.0,"ДостоинстваУдобно брызгать, расход небольшой.Н...",132
2,cd2bf942-9453-4c18-b9f8-711ba66d3a67,Toner mist,23.09.2024,Нұрайлым,5.0,"Құрбымнан көріп алғанмын, бетім құрғақ болғасы...",194
3,252a932f-a707-4586-b300-772ddffefdcd,Toner mist,13.07.2024,Ақерке,5.0,"Очень классная, качество супер, советую взять....",81
4,4b9dcb29-5743-4df2-a357-373c8129ae26,Toner mist,24.03.2024,Гульзада,3.0,"Мист шашатын жері істен шыққан, брак, сатушыға...",225
5,f395d024-62c2-4f99-8bb7-29b3fd19796e,Toner mist,14.04.2025,Рита,5.0,"Немного шиплет от того, что сразу даёт эффекты...",97
6,a323412b-45c3-4a5b-a271-af2991c6cdd5,Toner mist,04.02.2025,Коркем,5.0,Вся серия Skin 1004 супер Каспи как всегда луч...,85
7,1f6dde21-9551-4270-892a-d7b9b61f79d0,Toner mist,17.01.2025,Сымбат,5.0,Товар оригинал Спасибо большое магазину Korean...,171
8,9bb0238d-aff5-487c-8bfa-43109baefc54,Toner mist,04.12.2024,Женіс,5.0,Күшті.0 человека посчитали отзыв полезным,41
9,849b9f23-cfa6-4049-993a-531b608b4e3a,Dr.Althea 345,15.02.2024,Лилия,5.0,"Самый лучший, лёгкий, не вызывает аллергию, пр...",232
10,97157200-351f-4054-a433-b717ed270bac,Dr.Althea 345,03.01.2025,Индира,1.0,"Мне не подошел, не впитывается до конца, липко...",221
11,decdfc3b-8058-4908-a773-4b5ebc7cc3f6,Dr.Althea 345,12.11.2024,Ирина,5.0,"Огромное спасибо магазину POSH, доставили зака...",173
12,bb0ede29-65ad-4236-91e1-6823d609c10a,Dr.Althea 345,15.10.2024,Александра,5.0,Крем отлично подошел для моей жирной проблемно...,227
13,f5811a42-2876-4ba4-ab35-87b94c8902e1,Dr.Althea 345,11.03.2025,Малика,5.0,"Заказывала уже во второй раз, оригинал. Пока э...",191
14,e4b1297f-c066-46bb-b834-3b81823589c6,Dr.Althea 345,20.02.2025,Айнур,3.0,"Мне не подошло Нет никакого увлажнения, кожа к...",186
15,24bdf451-864a-4ac1-bb36-05725bb5922e,Dr.Althea 345,17.01.2025,Азиза,4.0,"Неплохой легкий крем с ниацинамидом в составе,...",632
16,c38b16e8-b941-4c83-8685-939de0c295b5,Dr.Althea 345,25.10.2024,Диана,5.0,"Замечательный крем, покупаю уже во второй раз....",193
17,cba42a27-f470-4ec4-8d9d-9c5ec84437d0,Dr.Althea 345,22.10.2024,Самира,5.0,"Доставили на 1 день раньше, за маску отдельное...",122
18,38d19608-5161-4121-8608-339646cd8602,Lagom,10.03.2022,Антон,5.0,"Купил даме сердца, она им намазала лицо и сраз...",237
19,603126a4-2fdb-4db1-b588-9b195e37f86a,Lagom,29.06.2023,Сымбат,0.0,"80мг написано в упаковке, но внутри нет и 20мг...",130
20,65cd2cdd-faf0-4bb2-a2c9-48ce744da5fc,Lagom,03.08.2022,Жанаргуль,5.0,ДостоинстваЛамеллярная формула. Качество. Увла...,511
21,6c62a078-1765-47cf-8613-7cdc828d478b,Lagom,31.08.2022,Сауле,3.0,"ДостоинстваБыстро впитывается, нежирный.Станда...",1084
22,5ce1b5ce-62b0-4bec-a71d-c1c538fd641d,Lagom,15.03.2022,Дильназ,5.0,"Наношу данный крем днём, нормальный. Самое гла...",235
23,ca28fa6e-52ec-4fcc-b71d-971701d59950,Lagom,20.12.2021,Дина,5.0,"ДостоинстваЭта фирма мой фаворит. Жаль, они вы...",190
24,5fc67734-d1eb-43cf-9131-ae8775a3e8b4,Lagom,05.02.2024,Алена,1.0,Купила в надежде на восстановление кожного бар...,592
25,f01eb6b4-945c-4ef1-a43e-7d59d350181c,Lagom,08.05.2023,Мадина,1.0,"Крем купила по положительным отзывам, должен б...",230
26,9bb432eb-591d-4f7c-b0da-7d07a3403509,Lagom,12.09.2022,Асхат,2.0,НедостаткиНе для жирной кожи точно Забивает по...,233
27,d4da1450-6c78-46c0-94b7-8243bab96372,telescopic тушь,06.12.2021,Венера,5.0,"ДостоинстваЯ была в стельку пьяная, с парнем п...",138
28,11660ccb-a428-41eb-948a-88a7b2379390,telescopic тушь,03.09.2022,Анастасия,5.0,ДостоинстваУстойчива к слезам. Удобна в примен...,288
29,75b5534c-ff75-4e60-aa8f-f5688a91b761,telescopic тушь,21.07.2021,Айнур,1.0,"НедостаткиУжасная тушь, повелась на отзывы, ре...",143
30,754774f7-82e8-4fd0-8e55-d00b1020b610,telescopic тушь,13.01.2020,Асель,5.0,"Советую всем. Не первый год с этой тушью, удли...",119
31,d67321d7-6dcd-4cf4-bd93-be8e2cd37f30,telescopic тушь,13.01.2020,Анар,5.0,"ДостоинстваОчень хорошая тушь, классно удлиняе...",91
32,975ebbf3-927f-4dcc-a0b3-994724a3f0ef,telescopic тушь,06.01.2020,Ольга,4.0,ДостоинстваХорошая удлиняющая тушь.40 человека...,71
33,668e82a2-0eb9-4a1e-811a-b657daa60c9c,telescopic тушь,06.09.2024,Айдана,1.0,"Оригинал емес, салыстырмалы түрде оригинал туш...",138
34,6cb95ad5-cc50-44f5-b604-71e6d228cee6,telescopic тушь,05.01.2023,Кристина,5.0,"ДостоинстваСамая лучшая тушь, прошлась пару ра...",96
35,a09f2b8b-dd5b-4d90-9bb8-3b5178e34bd8,telescopic тушь,12.12.2023,Милана,5.0,"Я рыдала целых 2 серии дорамы, тушь на месте, ...",108
36,b04d154c-bd98-406d-9de8-1a04916c2bd8,Бальзам,07.12.2021,Евгения,5.0,"ДостоинстваМягкий, комфортный в нанесении, с л...",183
37,7dfc2624-0127-4efd-b197-9973efb888e3,Бальзам,04.03.2024,Зулхумор,5.0,Ерінге арналған бальзамдар арасындағы ең керем...,353
38,060c68a0-eae9-4ff2-85de-834316cbd922,Бальзам,22.10.2022,Виктория,5.0,"ДостоинстваПриятно пахнет, хорошо увлажняет гу...",223
39,9c0da169-017f-4412-9dab-ee14691afe6b,Бальзам,21.10.2022,Кундыз,5.0,ДостоинстваЗапах нежный. Очень хороший вазелин...,99
40,d9c5225c-0c08-4c5b-a4bf-afda0bb5c73e,Бальзам,13.10.2022,Еңлік,5.0,"ДостоинстваХороший, увлажняет, легко наносится...",133
41,c130b34e-23b0-4925-9466-a738635b754c,Бальзам,18.10.2022,Елена,5.0,ДостоинстваХороший вазелин.3 человека посчитал...,62
42,d1dd5e33-ce81-4203-8f57-e9692a0c105c,Бальзам,11.10.2022,Саяжан,5.0,ДостоинстваПосле первого применения уже видно ...,148
43,cccbf22b-be74-4edd-904e-ee8800cf0d88,Бальзам,27.02.2025,Нұрай,5.0,"Ерні қыста да, жазда да жарылып үнемі бальзам ...",182
44,9ae68b3b-e19d-4c27-9e13-7bc8c59f55ec,Бальзам,22.12.2024,Рита,5.0,"Единственное, что спасает мои губы зимой, прия...",204
45,e0da8c82-e29c-4927-9005-ba3eaded9713,relouis пудра,21.04.2023,Карима,1.0,"НедостаткиНеудобно открывать, сыплется ужасно,...",210
46,73650932-54fd-402c-ae03-5bb4ea9212fe,relouis пудра,26.08.2022,Жамоат,3.0,"ДостоинстваБольшой объем, матирует очень хорош...",204
47,fee17335-de56-4728-a8f7-dea116d13a42,relouis пудра,26.10.2022,Альмира,3.0,"ДостоинстваСама пудра отличная, довольна.Недос...",238
48,55185f72-aa3b-463d-b41f-9a32c0e68036,relouis пудра,16.07.2021,Гүлназ,5.0,ДостоинстваПудра просто супер.Подходит для люб...,110
49,91fc4920-569a-432b-a4f3-c5da1c969755,relouis пудра,20.01.2024,Тамила,5.0,"Самая лучшая пудра для меня, пользуюсь ей почт...",272
50,7dc7a694-ac02-4ab6-8a02-3825ef1d8106,relouis пудра,25.04.2022,Сара,5.0,"ДостоинстваОчень классная пудра, невесомая и л...",110
51,4c93eb37-fde6-4a9d-ad7b-c997c0403356,relouis пудра,09.06.2022,Марина,4.0,ДостоинстваХорошо матирует.8 человека посчитал...,62
52,5432ce2e-5d26-4638-ab1c-7311e69d6556,relouis пудра,17.12.2024,Юлия,5.0,"Пудра классная, предупреждаю, сронжа в наборе ...",85
53,30dc57b6-48ef-4fe5-ac05-8ce0569df478,relouis пудра,24.04.2024,Аружан,1.0,Придаёт эффект сухой кожи.7 человека посчитали...,61